# Generated by Django 5.0.4 on 2024-05-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateTimeField()),
                ('cdkey', models.CharField(max_length=64, unique=True)),
                ('duration', models.IntegerField(choices=[(1, '1天'), (7, '7天'), (30, '30天'), (90, '90天'), (180, '180天'), (365, '365天')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('extract_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cdkey',
            },
        ),
    ]
