# Generated by Django 5.0.4 on 2024-05-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdkey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDKeyExtractRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=255)),
                ('extract_time', models.DateTimeField(auto_now_add=True)),
                ('cdkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extract_records', to='cdkey.cdkey')),
            ],
            options={
                'db_table': 'cdkey_extract_record',
            },
        ),
    ]
