# Generated by Django 5.0.4 on 2024-05-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdkey', '0002_cdkeyextractrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cdkey',
            table=None,
        ),
    ]
