# Generated by Django 5.0.4 on 2024-05-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('user_type', models.SmallIntegerField(choices=[(1, '管理员'), (2, '一级代理'), (3, '二级代理')])),
                ('status', models.BooleanField(default=True)),
                ('day_quota', models.IntegerField(default=0)),
                ('month_quota', models.IntegerField(default=0)),
                ('quota_updated_at', models.DateField(auto_now_add=True)),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
