# Generated by Django 5.0.4 on 2024-05-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_day_quota_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdkey',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdkey',
            name='validity_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cdkey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cdkeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cdkey',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_cdkeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
