# Generated by Django 5.0.4 on 2024-05-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdkey',
            name='validity_days',
            field=models.IntegerField(choices=[(1, '1 day'), (30, '30 days'), (90, '90 days'), (180, '180 days'), (365, '365 days'), (730, '730 days')], default=1),
        ),
    ]
