# Generated by Django 5.0.4 on 2024-05-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_cdkey_is_used_field_alter_cdkey_validity_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdkey',
            old_name='key',
            new_name='code',
        ),
    ]
